name: Python CI

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry
      - name: Install dependencies with Poetry
        run: |
          poetry install
      - name: Check code formatting with Ruff
        run: |
          poetry run ruff format --check .
      - name: Run Ruff linters
        run: |
          poetry run ruff check .

  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry
      - name: Install dependencies with Poetry
        run: |
          poetry install
      - name: Run tests with pytest
        run: |
          poetry run pytest . --log-format="%(levelname)s | %(message)s"
